[package]
name = "molecular"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.14", features = ["canvas", "advanced"]}
serde = { version = "1.0", features = ["derive"] }
pubchem = "0.1.1"
kurbo = "0"
rfd = "0.16"
serde_json = "1.0.148"

